spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/napuhanci
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
